### ISSUE TITLE
site.variables and theme.config files

### ISSUE THREAD

**Issue by yavuz** [wangaz/laravel-semantic-ui-css#1]
How do change site variables and theme config? Do you have any idea?

**Comment by thku** [comment]
This is a simple implementation of [Semantic-UI-CSS](https://github.com/Semantic-Org/Semantic-UI-CSS/). Therefore, this includes only the basic theme. I currently don't see a chance to implement the full Semantic UI as this exceeds the requirements of a simple LAMP environment. But I am open to any suggestions.
